GET http://localhost:3001/api/persons/ HTTP/1.1

###

GET http://localhost:3001/api/persons/6650fc50981c759035549682 HTTP/1.1

###

POST http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: application/json

{
  "name": "Mary Vásquez",
  "number": "035-5587456"
}

###

PUT http://localhost:3001/api/persons/66534719baf91d908a011ed2 HTTP/1.1
Content-Type: application/json

{
  "number": "035-58745638"
}

###

DELETE http://localhost:3001/api/persons/6650fc50981c759035549682  HTTP/1.1

###

GET http://localhost:3001/info HTTP/1.1