GET http://localhost:3003/api/blogs HTTP/1.1

###

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{ 
  "title": "SolesBot: Scam or Hidden Gem?", 
  "author": "Joshua C.", 
  "url": "https://www.joshuacontreras.com/money",
  "userId": "665b11e8b8972a8b2a247e86" 
}

###

DELETE http://localhost:3003/api/blogs/665b5f3dd99e6c23774e86b8 HTTP/1.1